runtime: nodejs18

entrypoint: npm start

instance_class: F1
automatic_scaling:
  min_instances: 1
  max_instances: 3 

env_variables:
  PG_USER: "postgres"
  PG_HOST: "/cloudsql/staysharp-442202:asia-southeast2:staysharp-instance"
  PG_DATABASE: "staysharp_database"
  PG_PASSWORD: "staysharp012"
  PG_PORT: "5432"
  PORT: "8080"

  