steps:
# Step 1
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/staysharp-backend'
    - '.'

# Step 2
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'gcr.io/$PROJECT_ID/staysharp-backend'

# Step 3
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'staysharp-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/staysharp-backend'
    - '--platform'
    - 'managed'
    - '--region'
    - 'asia-southeast2'
    - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/staysharp-backend'
